### PR TITLE
tr(cleanup): remove deprecated apis

### PR DESCRIPTION
**Pull request by educhastenier**
* tenant
* theme
* profileEntry

### CODE REVIEW

**Comment by rbioteau** [comment]
Is it possible to just deprecate them instead of deleting them ? 
It would be easier to have java client compatible with a range of bonita versions.

**Comment by akantcheff** [comment]
@rbioteau Deprecation is made on #64. This PR is preparing the next Bonita release when we will definitely remove them.

**Comment by akantcheff** [comment]
🆙 Are we agree that within this project we do not remove deprecated APIs?

**Comment by rbioteau** [comment]
Yes, depecrated API can't be removed yet as we use a single spec version (the latest) to generate a single java client

**Comment by akantcheff** [comment]
> Yes, depecrated API can't be removed yet as we use a single spec version (the latest) to generate a single java client

Closing this PR. Some modifications are transferred to #138

**Pull request closed without merging**
