### PR TITLE
feat(application): Update REST API for advanced applications.

### PR DESCRIPTION
**Pull request by vhemery**
Relates to [BPM-94](https://bonitasoft.atlassian.net/browse/BPM-94)

[BPM-94]: https://bonitasoft.atlassian.net/browse/BPM-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jeromecambon — APPROVED** [review]
LGTM!
I didn't see how to display the advanced application example

**Comment by vhemery** [comment]
> LGTM! I didn't see how to display the advanced application example

REST_API

**Review by jeromecambon — CHANGES_REQUESTED** [review]
- The examples (in the right pane) are not working as expected 
- Version of the API should be incremented

**Comment by jeromecambon** [comment]
> > LGTM! I didn't see how to display the advanced application example
> 

Thanks for the video, but this is not what I meant, I an speaking about the examples in the right panel

**Comment by vhemery** [comment]
The array example can't use references to different schema locations, so I had to copy values in it.

**Comment by vhemery** [comment]
**Note:**
Deprecated enpoints use the legacy application.

This is not an error !

**Review by jeromecambon — APPROVED** [review]
LGTM

**Pull request merged**
